### ISSUE TITLE
thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by Kyant0** [nnethercote/dhat-rs#41]
```toml
[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
dhat = { version = "0.3.3" }

[features]
dhat-heap = []
dhat-ad-hoc = []

[profile.release]
debug = 1

```

```rust
#[cfg(feature = "dhat-heap")]
#[global_allocator]
static ALLOC: dhat::Alloc = dhat::Alloc;

fn main() {
    #[cfg(feature = "dhat-heap")]
    let _profiler = dhat::Profiler::new_heap();
    println!("Hello, world!");
}
```

Running result with `cargo run --features dhat-heap`

thread 'main' has overflowed its stack
error: process didn't exit successfully: `target\release\cli.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)

Process finished with exit code -1073741571 (0xC00000FD)
